import { Opinion } from './types';

export const TOPIC = {
  title: "生命的短暂本质，究竟要求我们热烈拥抱还是超然接受？",
  description: "这个话题探讨面对生命短暂性时的哲学态度，涉及存在主义、享乐主义、斯多葛主义等多个哲学流派的思考。",
  dimensions: [
    {
      id: "existence",
      name: "存在属性",
      question: "生命是否本质上是转瞬即逝的？",
      description: "触及时间哲学",
    },
    {
      id: "value",
      name: "价值选择",
      question: "面对有限性，积极投入与保持距离哪种更具智慧？",
      description: "涉及存在主义与斯多葛主义",
    },
    {
      id: "meaning",
      name: "意义建构",
      question: "欢愉体验与精神超越能否兼得？",
      description: "连接享乐主义与超验哲学",
    },
  ],
};

// Mock opinions for our star map
export const MOCK_OPINIONS: Opinion[] = [
  {
    id: "1",
    title: "生命的本质是流动变化，时间是人为的度量",
    content: "从物理学角度看，时间并非绝对存在，而是观察者感知的结果。生命的短暂性是相对的概念，在宇宙尺度上，所有存在都是永恒的一部分。",
    dimension: "existence",
    author: "AI生成",
    support: 78,
    position: { x: 0.3, y: 0.2 }, // Position in the 2D space
    embraceScore: 0.6, // 0: fully detached, 1: fully embracing
    perspectiveScore: 0.3, // 0: individual perspective, 1: cosmic perspective
  },
  {
    id: "2",
    title: "人类感知中的时间长短是主观的，取决于体验质量",
    content: "心理学研究表明，我们的时间感知与情绪状态和专注程度密切相关。在心流状态中，时间感消失；在痛苦中，时间被拉长。因此，关注体验质量比关注时间更有意义。",
    dimension: "existence",
    author: "用户A",
    support: 65,
    position: { x: 0.5, y: 0.3 },
    embraceScore: 0.8,
    perspectiveScore: 0.2,
  },
  {
    id: "3",
    title: "生命本质上是永恒的，只是形式在不断变化",
    content: "从能量守恒定律看，生命中的物质和能量不会消失，只会转化。我们的意识可能是宇宙意识的一部分，生命的个体形式是暂时的，但其本质是永恒的。",
    dimension: "existence",
    author: "AI生成",
    support: 42,
    position: { x: 0.2, y: 0.7 },
    embraceScore: 0.4,
    perspectiveScore: 0.8,
  },
  {
    id: "4",
    title: "短暂性是所有存在的根本特质，无物可逃",
    content: "从热力学第二定律看，熵增是不可逆的。所有结构最终都会瓦解，包括生命。认识到这一点不是悲观主义，而是对现实的清醒认知。",
    dimension: "existence",
    author: "用户B",
    support: 59,
    position: { x: 0.1, y: 0.5 },
    embraceScore: 0.3,
    perspectiveScore: 0.7,
  },
  {
    id: "5",
    title: "全情投入是最高智慧，因为只有体验才是真实的",
    content: "存在主义提倡，面对生命的有限性，我们应当通过真实的体验和选择定义自己。全情投入当下，创造自己的意义，是面对短暂性的最佳回应。",
    dimension: "value",
    author: "用户C",
    support: 87,
    position: { x: 0.8, y: 0.3 },
    embraceScore: 0.9,
    perspectiveScore: 0.4,
  },
  {
    id: "6",
    title: "保持超然距离才能看清生命全貌，避免执着痛苦",
    content: "斯多葛主义认为，情绪痛苦来自于我们对无法控制事物的执着。接受生命的自然规律，包括其短暂性，才能达到内心平静和自由。",
    dimension: "value",
    author: "AI生成",
    support: 63,
    position: { x: 0.3, y: 0.8 },
    embraceScore: 0.2,
    perspectiveScore: 0.8,
  },
  {
    id: "7",
    title: "两种态度可以辩证结合，知道何时投入何时抽离",
    content: "智慧不在于选择一种固定态度，而在于根据情境灵活调整。有时需要全情投入，有时需要保持距离，这种平衡是真正的人生艺术。",
    dimension: "value",
    author: "用户D",
    support: 92,
    position: { x: 0.6, y: 0.6 },
    embraceScore: 0.5,
    perspectiveScore: 0.5,
  },
  {
    id: "8",
    title: "投入与距离不是选择而是生命不同阶段的自然状态",
    content: "人生不同阶段有不同的任务和挑战。年轻时倾向于全情投入体验，年长时自然发展出超然视角，这是生命自然智慧的体现。",
    dimension: "value",
    author: "AI生成",
    support: 45,
    position: { x: 0.7, y: 0.7 },
    embraceScore: 0.6,
    perspectiveScore: 0.6,
  },
  {
    id: "9",
    title: "享乐与超越是虚假二分，深度体验即为超越",
    content: "在艺术、爱、创造等深度体验中，个体超越了日常自我，连接到更大的存在。这种状态既是享乐的顶峰，也是超越的开端。",
    dimension: "meaning",
    author: "用户E",
    support: 76,
    position: { x: 0.8, y: 0.4 },
    embraceScore: 0.8,
    perspectiveScore: 0.7,
  },
  {
    id: "10",
    title: "精神超越是对享乐追求的必然超越，是人类成长的必经阶段",
    content: "随着心智成熟，人们自然会从直接享乐转向追求更高层次的意义。这是心理学中自我超越的表现，代表精神成长的自然轨迹。",
    dimension: "meaning",
    author: "AI生成",
    support: 53,
    position: { x: 0.4, y: 0.9 },
    embraceScore: 0.3,
    perspectiveScore: 0.9,
  },
  {
    id: "11",
    title: "意义在于创造，而非体验或超越",
    content: "生命的意义既不在于享受当下，也不在于追求超越，而在于创造性地改变世界。通过我们的行动和创造，我们在短暂的生命中为世界增添永恒的价值。",
    dimension: "meaning",
    author: "用户F",
    support: 68,
    position: { x: 0.6, y: 0.2 },
    embraceScore: 0.7,
    perspectiveScore: 0.4,
  },
  {
    id: "12",
    title: "生命意义是个体建构的，无需在既有框架中选择",
    content: "各种哲学体系提供的是预设的意义框架，而真正的自由在于超越这些框架，创造自己独特的生命意义叙事。每个人都是自己生命意义的作者。",
    dimension: "meaning",
    author: "AI生成",
    support: 71,
    position: { x: 0.9, y: 0.6 },
    embraceScore: 0.6,
    perspectiveScore: 0.5,
  },
];
