# Wrangler 配置文件 - Cloudflare Pages 部署配置

name = "mcpapi"
compatibility_date = "2025-03-16"

# Pages 特定配置
[build]
command = "npm run build"
[build.upload]
format = "service-worker"

# Pages 构建输出目录 - 这是关键配置
pages_build_output_dir = ".next"

# 环境变量配置
[vars]
APP_ENV = "production"

# 兼容性标志
[compatibility_flags]
nodejs_compat = true
