# Wrangler 配置文件 - Cloudflare Pages 部署配置

name = "mcpapi"
compatibility_date = "2025-03-16"

# Pages 特定配置
[build]
command = "npm run build"
output_directory = ".next"
pages_build_output_dir = ".next"


[build.upload]
format = "directory"
include = [".next/**/*"]
exclude = [
  ".next/cache/**",
  ".next/server/chunks/**/*.js.map",
  ".next/server/pages/**/*.js.map",
  ".next/cache/webpack/**"
]

# 环境变量配置
[site]
bucket = ".next"

[env.production]
vars = { APP_ENV = "production" }

# 兼容性标志
[compatibility_flags]
nodejs_compat = true
